name:                union
version:             0.1.0.0
github:              "githubuser/union"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/union#readme>

dependencies:
- base >= 4.7 && < 5
- mira >= 2.0.0 && < 2.1
- containers >= 0.6.5.1 && < 6.6
- QuickCheck >= 2.14.2 && < 2.15  
library:
  source-dirs: src

executables:
  union:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - union

tests:
  union-test:
    main:                RunTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - union